version: '2'
services:
  mysql:
    image: mysql:5.7
    container_name: localhost-mysql
    working_dir: /var/www
    volumes:
      - .:/var/www
      - ./storage/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=homestead
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
    ports:
      - "3306:3306"
  php-fpm:
    build: config/php-fpm
    container_name: tcp-leaserunner-php-fpm
    working_dir: /var/www
    volumes:
      - .:/var/www
      - ./config/php-fpm/php-ini-overrides.ini:/etc/php/7.3/fpm/conf.d/99-overrides.ini
    environment:
      XDEBUG_CONFIG: "remote_host=192.168.220.1 remote_enable=1 remote_connect_back=1"
      PHP_IDE_CONFIG: "serverName=Docker"
  redis:
    image: redis:alpine
    container_name: localhost-redis
  webserver:
    image: nginx:alpine
    container_name: localhost-webserver
    working_dir: /var/www
    volumes:
      - .:/var/www
      - ./config/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./config/nginx/my-site.com.crt:/etc/nginx/my-site.com.crt # New Line!
      - ./config/nginx/my-site.com.key:/etc/nginx/my-site.com.key # New Line!
    ports:
      - "80:80"
      - "443:443"